[package]
name = "i18n-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rs-i18n = {path = "../rs-i18n"}
strum = { version = "0.25", features = ["derive"] }